### ISSUE TITLE
Wayland: crash when dropping items into the side-pane

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#838]
##### Steps to Reproduce (for bugs)

1. Under Wayland and in pcmanfm-qt, DND an item from the view into the side-pane.
2. In the DND menu (which is misplaced BTW), click cancel.

Then a crash happens. Its partial backtrace:
```
#0  0x00007fcae6b6cde6 in  () at /usr/lib/libQt5Core.so.5
#1  0x00007fcae6b6dfcf in QMimeData::urls() const () at /usr/lib/libQt5Core.so.5
#2  0x00007fcae7bf9c60 in Fm::PlacesModel::dropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) () at /usr/lib/libfm-qt.so.11
#3  0x00007fcae6b1c86a in QAbstractProxyModel::dropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) () at /usr/lib/libQt5Core.so.5
#4  0x00007fcae78256ac in QAbstractItemView::dropEvent(QDropEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007fcae75f7558 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#6  0x00007fcae76a5793 in QFrame::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007fcae6b4c7d2 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#8  0x00007fcae75c0b0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007fcae75c7016 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007fcae6b4cb68 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#11 0x00007fcae7617a94 in  () at /usr/lib/libQt5Widgets.so.5
#12 0x00007fcae75c0b1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007fcae6b4cb68 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#14 0x00007fcae6f2aecf in QGuiApplicationPrivate::processDrop(QWindow*, QMimeData const*, QPoint const&, QFlags<Qt::DropAction>, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) () at /usr/lib/libQt5Gui.so.5
#15 0x00007fcae6f091c6 in QWindowSystemInterface::handleDrop(QWindow*, QMimeData const*, QPoint const&, QFlags<Qt::DropAction>, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) () at /usr/lib/libQt5Gui.so.5
#16 0x00007fcae2ecc4fb in  () at /usr/lib/libQt5WaylandClient.so.5
#17 0x00007fcae5542536 in  () at /usr/lib/libffi.so.8
#18 0x00007fcae553f037 in  () at /usr/lib/libffi.so.8
#19 0x00007fcae7d27645 in  () at /usr/lib/libwayland-client.so.0
#20 0x00007fcae7d27e03 in  () at /usr/lib/libwayland-client.so.0
#21 0x00007fcae7d27ffc in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#22 0x00007fcae2ea8b36 in QtWaylandClient::QWaylandDisplay::flushRequests() () at /usr/lib/libQt5WaylandClient.so.5
...
```

##### Possible Solution
Apparently, under Wayland, `QMimeData` is destroyed after showing or closing the DND menu. So, the needed info should be acquired before showing that menu. I think that's also safer under X11.

 Will make a PR.

##### Context

Have been testing various aspects of LXQt apps under Wayfire, hunting Wayland bugs.

##### System Information

* Latest git LXQt.

**Comment by stefonarch** [comment]
Cannot reproduce here, neither with tree view nor with places.

**Comment by selairi** [comment]
I cannot reproduce, also. I tested it under Sway.

**Comment by tsujan** [comment]
@stefonarch, @selairi

It may depend on factors unknown to us, but https://github.com/lxqt/libfm-qt/pull/839 is not only more logical but also safer, under X11 too.
