### ISSUE TITLE
Crash in `PathBar::closeEditor`

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#919]
I don't know how to reproduce it, but it happened to pcmanfm-qt while I was checking something not related to the path-bar:

```
#0  0x00007f9998d031f3 in Fm::PathBar::closeEditor() () at /usr/lib/libfm-qt6.so.13
#1  0x00007f999759134a in  () at /usr/lib/libQt6Core.so.6
#2  0x00007f99986eb5f0 in QLineEdit::focusOutEvent(QFocusEvent*) () at /usr/lib/libQt6Widgets.so.6
#3  0x00007f9998d01f0e in Fm::PathEdit::focusOutEvent(QFocusEvent*) () at /usr/lib/libfm-qt6.so.13
#4  0x00007f99985bd064 in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#5  0x00007f999857136b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#6  0x00007f999753b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#7  0x00007f999857d5f1 in  () at /usr/lib/libQt6Widgets.so.6
#8  0x00007f99985b69a1 in QWidget::clearFocus() () at /usr/lib/libQt6Widgets.so.6
#9  0x00007f99985a8708 in QWidget::~QWidget() () at /usr/lib/libQt6Widgets.so.6
#10 0x00007f9998863d11 in QListView::~QListView() () at /usr/lib/libQt6Widgets.so.6
#11 0x00007f999894f904 in  () at /usr/lib/libQt6Widgets.so.6
#12 0x00007f999894f038 in QCompleter::~QCompleter() () at /usr/lib/libQt6Widgets.so.6
#13 0x00007f9998d00bff in Fm::PathEdit::~PathEdit() () at /usr/lib/libfm-qt6.so.13
#14 0x00007f9998d00cae in Fm::PathEdit::~PathEdit() () at /usr/lib/libfm-qt6.so.13
#15 0x00007f999757d57b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#16 0x00007f99985a8a39 in QWidget::~QWidget() () at /usr/lib/libQt6Widgets.so.6
#17 0x00007f9998c4e7f8 in  () at /usr/lib/libfm-qt6.so.13
#18 0x00005591d8f01139 in  ()
#19 0x00005591d8eeb363 in  ()
#20 0x00007f999759140d in  () at /usr/lib/libQt6Core.so.6
#21 0x00007f9997f03c37 in QAction::activate(QAction::ActionEvent) () at /usr/lib/libQt6Gui.so.6
#22 0x00007f9997f05168 in QAction::event(QEvent*) () at /usr/lib/libQt6Gui.so.6
#23 0x00007f999857136b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#24 0x00007f999753b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#25 0x00007f9997f1b50a in QShortcutMap::dispatchEvent(QKeyEvent*) () at /usr/lib/libQt6Gui.so.6
#26 0x00007f9997c07f80 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) ()
    at /usr/lib/libQt6Gui.so.6
#27 0x00007f9997ba639a in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) ()
    at /usr/lib/libQt6Gui.so.6
#28 0x00007f9997c0f6ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt6Gui.so.6
#29 0x00007f999375fb6f in  () at /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#30 0x00007f9998310a61 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#31 0x00007f999836dc29 in  () at /usr/lib/libglib-2.0.so.0
#32 0x00007f999830e112 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#33 0x00007f9997732794 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt6Core.so.6
#34 0x00007f9997545623 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#35 0x00007f999753f1f8 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#36 0x00005591d8ee813c in  ()
#37 0x00007f9996a27cd0 in  () at /usr/lib/libc.so.6
#38 0x00007f9996a27d8a in __libc_start_main () at /usr/lib/libc.so.6
#39 0x00005591d8ee8265 in _start ()
```

**Comment by tsujan** [comment]
The above backtrace was for the Qt6 branch, but luckily I found a way to reproduce the crash, which happens with the current Qt5-based libfm-qt too:

 1. Enable the path buttons in pcmanfm-qt, and disable the split view mode.
 2. Click into an empty space of the the path-bar to show the path-edit.
 3. While the path-edit has focus, press F6 (to enable the split view).

Then pcmanfm-qt crashes, but the crash is in libfm-qt. The Qt5 backtrace is the same as the Qt6 one.
